build/docker: Use older ffi (1.9.14)
`gem install fbm` tries to install the ffi gem too, which has a
problem in newer versions (>= 1.9.15) - see [1]:
"AbstractMemory.c:349:48: error: expected ')' before 'PRIsVALUE'"

To bypass the newly introduced issues, use the old version.

[1] https://jira.opnfv.org/browse/ARMBAND-191

JIRA: ARMBAND-191

Change-Id: I29896f8af0b0023050bd8ce7cb5189bfb833f2dc
Signed-off-by: Alexandru Avadanii <Alexandru.Avadanii@enea.com>