retry on socket.timeout and socket.error in discovery_waiting_loop
we were getting socket.timeouts in discovery_waiting_loop

the exception was terminating the loop, instead
catch the exception and retry.

we probably need to close/open to re-login into the fuel master VM

failure:

Traceback (most recent call last):
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 437, in <module>
    main()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 434, in main
    sys.exit(d.run())
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 282, in run
    deploy_success = self.deploy()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 273, in deploy
    return self.deploy_env()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 248, in deploy_env
    return dep.deploy()
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 328, in deploy
    self.wait_for_discovered_blades()
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 190, in wait_for_discovered_blades
    all_discovered = self.discovery_waiting_loop(discovered_macs)
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 207, in discovery_waiting_loop
    node_list = parse(self.ssh.exec_cmd('fuel node list'))
  File "/root/fuel/opnfv-fuel/deploy/ssh_client.py", line 56, in exec_cmd
    response = stdout.read().strip()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 192, in read
    new_data = self._read(self._DEFAULT_BUFSIZE)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1240, in _read
    return self.channel.recv(size)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 615, in recv
    raise socket.timeout()
timeout

we also need to catch socket.error and retry

Not sure why we are getting socket error connect from fuel master host
to VM.

Traceback (most recent call last):
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 437, in <module>
    main()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 434, in main
    sys.exit(d.run())
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 282, in run
    deploy_success = self.deploy()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 273, in deploy
    return self.deploy_env()
  File "/root/fuel/opnfv-fuel/deploy/deploy.py", line 248, in deploy_env
    return dep.deploy()
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 334, in deploy
    delete(self.updated_dea_file)
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 183, in wait_for_discovered_blades
    all_discovered = self.discovery_waiting_loop(discovered_macs)
  File "/root/fuel/opnfv-fuel/deploy/deploy_env.py", line 208, in discovery_waiting_loop
    if node_list:
  File "/root/fuel/opnfv-fuel/deploy/ssh_client.py", line 52, in exec_cmd
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 420, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 705, in open_session
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 826, in open_channel
    raise e
error: [Errno 104] Connection reset by peer

Change-Id: I46c1444246c04219e64fdb6b5dbfbb100f4e2ab8
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>